name: bsp
description: Radxa BSP Build Tool
inputs:
  target:
    required: true
  edition:
    required: true
  revision:
    retuired: false
    default: 1
  artifacts:
    required: false
    default: 'false'
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: openhd/bsp
        submodules: true
    - name: Install dependency
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y qemu-user-static binfmt-support
    - name: Build
      shell: bash
      run: |
        echo "debug-step"
        mkdir .output
        pushd .output
        ../bsp --long-version -r ${{ inputs.revision }} ${{ inputs.target }} ${{ inputs.edition }}
        popd
    - name: debug
      shell: bash
      run: |
        ls -a 